# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - havoc-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   defaults:
  #     run:
  #       working-directory: ./Havoc-API

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: "8.0.x"

  #     - name: Restore dependencies
  #       run: dotnet restore

  #     - name: Build solution
  #       run: dotnet build --configuration Release --no-restore

  #     - name: Run Unit Tests
  #       run: dotnet test --no-restore --verbosity normal

  build:
    runs-on: "ubuntu-latest"
    # needs: test
    steps:
      - uses: actions/checkout@v2


      - name: Create Production Settings
        run: |
          sed -i 's|\${ConnectionStrings__Default}|${{ secrets.CONNECTIONSTRING}}|g' ./Havoc-API/Havoc-API/appsettings.Production.json
          sed -i 's|\${JWT__Key}|${{ secrets.JWTKEY }}|g' ./Havoc-API/Havoc-API/appsettings.Production.json
          sed -i 's|\${JWT__Audience}|${{ secrets.SPAURL }}|g' ./Havoc-API/Havoc-API/appsettings.Production.json
          sed -i 's|\${JWT__Issuer}|${{ secrets.APIURL }}|g' ./Havoc-API/Havoc-API/appsettings.Production.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://havocimages.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_086dabfadc0143fd90a768bdd51ddfdf }}
          password: ${{ secrets.AzureAppService_ContainerPassword_6c329044ff7d449991b49c0beb635f61 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: havocimages.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_086dabfadc0143fd90a768bdd51ddfdf }}/api/havoc-api:${{ github.sha }}
          file: ./Havoc-API/Dockerfile
          secrets: |
            jwt_key=${{ secrets.JWTKEY }}
            db_connection=${{ secrets.CONNECTIONSTRING }}
            api_url=${{ secrets.APIURL }}
            spa_url=${{ secrets.SPAURL }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "havoc-api"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_dcfb90adbcab4d12ad9dbe02d0c02af4 }}
          images: "havocimages.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_086dabfadc0143fd90a768bdd51ddfdf }}/api/havoc-api:${{ github.sha }}"
